export enum JobItemType {
  ORIGINAL_ZIP = "ORIGINAL_ZIP",
  RAW_ZIP = "RAW_ZIP",
  CROPPED_ZIP = "CROPPED_ZIP",
  TXT_DOCUMENT = "TXT_DOCUMENT",
  DOCX_DOCUMENT = "DOCX_DOCUMENT",
  THUMBNAIL = "THUMBNAIL",
  CROPPED_THUMBNAIL = "CROPPED_THUMBNAIL",
}

